FROM node:23-slim
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
COPY .env.docker ./.env
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start:prod"]
# To build docker image run:
# sudo docker buildx build -t nest-dgt:1 .