services:
  db:
    container_name: postgresSQL-DGTCW
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "500:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4-DGTCW
    image: dpage/pgadmin4:8.13
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
  nest-dgt:
    container_name: nest-dgt
    image: nest-dgt:1
    restart: always
    ports:
      - "3000:3000"
  java-dgt:
    container_name: java-dgt
    image: java-dgt:1
    restart: always
    depends_on:
      - db
      - nest-dgt
    links:
      - nest-dgt

volumes:
  pgdata:
  pgadmin: